# Generated by Django 5.0.1 on 2024-02-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='img',
            new_name='background_image',
        ),
    ]
